apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgA5AfsoT6FBrK2SKpj2cNqkFsMeguUp5jvb+MP8qpWM2Ncl0H1zDex8u0yYkPlYhxrYSmU1ryER2PY3ESV7MHRyO3wLhzeDgHl1KO/JbpKJdokk7WmZyl21UdfPFNDKDLdzf9aM1Vr4oayF7Pb41aMOc+PfIhqSzVoSBFL8dBIiXhg3U9WoISC+nKk/bIpC+0nqNk1ywYtl1Pz0vMu9EDcoo/qgj8k2flowuLcVK0kGX72N4vN8lEjbBJk4imKffQwoqNgWzgX6+Bps6C7zeAKEP1Fp563jWJR2qVGBgCUVCsQ0gLRZJQfLqgsoRdYQiSg6a6mSPiamawhKOnya3MNYUZD1qXCfJ7wsUWteiURE8QcGVpGOwZRsh03klLPn7A5yPGj/jHj96AMDtc4fWG+MP/2DSCc4AIe78nu09odyvOTRiXbyl2rFp2/bMWMUFF68XS7QD2XElbByDW5bzZifKiGK6BJT1JgDBR9LnGTExOGSuqKM+OPOPhQLxHtemhucYQaUKECqVjdQhgaeSjIOkt9xgvDyAA2q651so1mwqFBnaKdIL7/YKti9ZqpcbxVucvyzSlQ0rgWrwjTL5ngkgTv1DlxxgCEuUpTy9TtOGUBQjiG0oWNj0W4fbk4jJmwiifBOSySwy0nvjmn2etssZ2+O58zXf98ybKazOtnr6xsK2X9JGEbj0UXHuh+tP338SyVAMEC6/vI8T8XEOvRDndoO+Q==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
