apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCSfE/v0mEexopJWbsx2iuAEmhYjYYRfRgDl006RpWpZLwaSu2coXJU2rhIUFIvNnFwuCIz6HzGhvF+PW9BjGJKoSJcd7nyaZy7v9lvh3bVmVjhSEdmJrk+OMZaY+h+j5gQz/z7XlB1b/8tdXfyv724KgznfivaIttRsq4R7qY8IQcDQtcR1korUxpmc5SxhGI2bDG2T/xtClqxmBccMM9Ob3NBSVwgUMxpexeShqoa5LuvtutjzYZXhu/Q1JHE9Ze3UON3IOOMoDNwiETkkPvWGR4PbdFgV0TdnnBNX2O/7ebGYKgrMqIZI5pcUmb28fuj8edP07Yf5AAJg12xWrvkA4CiqDg6mKIOQg8Mj2KcsPnUs5gZneJP2MH+/P4N4ahRjk8JBRO2MmIyu5Yt8sd/j85qwY7vZAtbXEwHATNztKVcDDNAOFcduzD3mV9EfzOdbWL2mLAYy4gJnZUQgb1DYRdHGhSJlE3WxAjhx4TDBA2f3mpB1aleIChXxZo2hKNbYYnRMlUSSHE+npAK7hl4MXGx8JbQ8WwxJMyr6pi31+lH7Eot9DCFy6+dMiLRErbLzIjQqRVd3580YOco8WOXZnaWdsgTLrXn2OHgXkueIYh0zNt2G7kJgIkEdv6WKzvLE5cd0m4QdzsF2/48CF1E0m667DdAB+pxEKSYe2uOOO25rghj599Su2z2o8XNIQlpNAbT6l5gnrk+vW9hUrEj+JOFYw==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
